resources:
  repositories:
    - repository: templates
      type: github
      name: kasunch/conan-templates
      ref: kasun
      endpoint: kasunch

extends:
  template: .ci/azure.yml@templates
  parameters:
    conanLoginUsername: $(CONAN_LOGIN_USERNAME)
    conanPassword: $(CONAN_PASSWORD)
    conanArchs: "x86_64"
    conanBuildTypes: "Release"
    conanStableBranchPattern: "stable/*"
    linuxGCCVersions: "7"
    vsVersions: "16"
    appleClangVersions: "10"
    splitByBuildTypes: "true"
    requireMoreDiskSpace: "true"
